version: '3.1'

services:
  mongodb:
    image: mongo:6.0.3
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./dump:/dump
    restart: always
    networks:
      - mongodb_network

volumes:
  mongodb-data:
    driver: local
    name: data

networks:
  mongodb_network:
    external: true
